export interface ILowStockAlert { id: string; product_id: string; variant_id: string; product_name: string; variant_name: string; stock: number; threshold: number; email_sent_at: string | null; telegram_sent_at: string | null; created_at: string; }
export interface ISupplier { id: string; name: string; email: string | null; phone: string | null; address: string | null; notes: string | null; is_active: boolean; created_at: string; }
export interface IPurchaseOrderItem { id: string; product_id: string; variant_id: string; product_name: string; variant_name: string; variant_sku: string | null; ordered_quantity: number; received_quantity: number; unit_cost: string; }
export interface IPurchaseOrder { id: string; supplier_id: string; supplier: ISupplier; status: string; currency: string; total_cost: string; expected_at: string | null; notes: string | null; created_at: string; items: IPurchaseOrderItem[]; }
export interface IReturnItem { id: string; order_item_id: string; product_id: string; variant_id: string; product_name: string; variant_name: string; quantity: number; restock_quantity: number; }
export interface ISalesReturn { id: string; order_id: string; status: string; reason: string; notes: string | null; refund_amount: string; received_at: string | null; refunded_at: string | null; created_at: string; items: IReturnItem[]; }
export interface IBestSeller { product_id: string; product_name: string; variant_id: string; variant_name: string; units_sold: number; revenue: string; }
export interface IForecast { product_id: string; product_name: string; variant_id: string; variant_name: string; current_stock: number; units_sold: number; daily_velocity: number; forecast_units: number; days_of_cover: number | null; suggested_reorder: number; }
export interface IOperationsReport { days: number; forecast_days: number; total_orders: number; total_units: number; total_revenue: string; best_sellers: IBestSeller[]; forecast: IForecast[]; daily_sales: { date: string; orders: number; units: number; revenue: string }[]; }
